Generated export autocommit from mamba.ru

diff --git a/.github/workflows/mamba-ready.yml b/.github/workflows/mamba-ready.yml
--- a/.github/workflows/mamba-ready.yml
+++ b/.github/workflows/mamba-ready.yml
@@ -21,7 +21,6 @@ jobs:
           ./boost-setup.sh
         working-directory: ./.github/workflows
 
-
       - name: Сборка
         run: |
           make coverage-report
@@ -32,7 +31,6 @@ jobs:
              export CODECOV_TOKEN=${{ secrets.CODECOV_TOKEN }}
              bash <(curl -s https://codecov.io/bash)
           popd
-
 
       - name: Плучение списка пул-реквестов mamba-ready
         uses: octokit/request-action@v2.x
@@ -47,7 +45,8 @@ jobs:
       - name: Пул-реквест mamba-ready уже создан
         if: contains(steps.list_pull_requests.outputs.data, 'id')==true
         run: |
-          echo "Ну и ладно"
+          echo "Удаляем mamba-ready"
+          git push https://${{ secrets.ACCESS_TOKEN }}@github.com/${GITHUB_REPOSITORY}.git :mamba-ready || echo "Delete mamba-ready FAIL"
 
       - name: Создаем Пул-реквест mamba-ready
         uses: octokit/request-action@v2.x
@@ -60,3 +59,7 @@ jobs:
           base: "master"
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+
+      - name: Удаляем бранч mambaru
+        run: |
+          git push https://${{ secrets.ACCESS_TOKEN }}@github.com/${GITHUB_REPOSITORY}.git :mambaru || echo "Delete mambaru FAIL"
